### ISSUE TITLE
Wiring Diagram Updates

### ISSUE THREAD

**Issue by dtauer** [stevekinney/nodebots-v2#1]
These are the wiring diagrams the need to be updated:

**single-led.svg**

- Move transistor up to row I
- move lead (yello) over to J23 (match resister)

**potentiometer.svg**

- Does fritzing have a sensor that matches your the kit with the middle prong on the oposite side. if so let's add that and run the wire to it.
- So move the yellow wire which goes to A0 in the board from it's current spot to C2

**photoresistor.svg**

- resistor and A1 wire need to be after the sensor (swap resistor and sensor)
- Move sensor to F11-F7
- Move resistor to H14-H11

**Comment by stevekinney** [comment]
@dtauer I _think_ I got everything, but you might want to double check.

**Comment by dtauer** [comment]
@stevekinney These look great! Thanks for fixing!
